# Generated by Django 4.1.2 on 2022-10-10 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_ref', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('delivery_date', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3)])),
                ('delivery_town', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('bayer', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('seller', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('status', models.CharField(choices=[('In progress', 'In progress'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=16)),
                ('description', models.TextField(default='', max_length=300)),
            ],
        ),
    ]
