# Generated by Django 4.1.2 on 2022-10-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentmodel',
            name='status',
            field=models.CharField(choices=[('In progress', 'In progress'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], default='In progress', max_length=16),
        ),
    ]
