# Generated by Django 4.1.2 on 2022-10-10 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments_app', '0002_alter_shipmentmodel_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShipmentModel',
            new_name='Shipment',
        ),
    ]
