# Generated by Django 4.1.2 on 2022-10-11 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments_app', '0003_rename_shipmentmodel_shipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='bayer',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='delivery_date',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='delivery_town',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='seller',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_ref',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
